---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-logoperator-qi1999-io-v1-collectrule
  failurePolicy: Fail
  name: mcollectrule.kb.io
  rules:
  - apiGroups:
    - logoperator.qi1999.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - collectrules
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-logoperator-qi1999-io-v1-collectrule
  failurePolicy: Fail
  name: vcollectrule.kb.io
  rules:
  - apiGroups:
    - logoperator.qi1999.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - collectrules
  sideEffects: None
