# permissions for end users to view collectrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: collectrule-viewer-role
rules:
- apiGroups:
  - logoperator.qi1999.io
  resources:
  - collectrules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - logoperator.qi1999.io
  resources:
  - collectrules/status
  verbs:
  - get
