# permissions for end users to view logbackends.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logbackend-viewer-role
rules:
- apiGroups:
  - logoperator.qi1999.io
  resources:
  - logbackends
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - logoperator.qi1999.io
  resources:
  - logbackends/status
  verbs:
  - get
